import React from "react";
const recom = [
  {
    "id": "1",
    "ASIN": "B0728DT431",
    "BRAND": "Elie Tahari",
    "Title": "elie tahari black ruffled vneck long sleeves blouse shirt black xlarge ",
    "Euclidean_similarity": "2.220446049250313e-16",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41fSZznuMRL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "2",
    "ASIN": "B00NNFP22K",
    "BRAND": "coromose",
    "Title": "coromose women vneck chiffon long sleeve shirt blouse black ",
    "Euclidean_similarity": "0.44529980377477096",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41pq8OnGRoL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "3",
    "ASIN": "B01N9N5VSP",
    "BRAND": "Unomatch",
    "Title": "unomatch women collar neck long sleeves formal blouse black small black ",
    "Euclidean_similarity": "0.46153846153846145",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41bV9qSsCwL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "4",
    "ASIN": "B01EZ6XKR4",
    "BRAND": "Ferrari",
    "Title": "ferrari ladies black vneck tee shirt xlarge ",
    "Euclidean_similarity": "0.4758575816390409",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/419fqKbQu-L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "5",
    "ASIN": "B06XWYWG44",
    "BRAND": "Unomatch",
    "Title": "women lace fit bust shirt blouse black xs black ",
    "Euclidean_similarity": "0.49825479399574546",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/418wTQY494L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "6",
    "ASIN": "B01B7HW7J6",
    "BRAND": "MICHAEL Michael Kors",
    "Title": "michael kors long sleeves button blouse shirt top tunic black 10 ",
    "Euclidean_similarity": "0.49825479399574546",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/410xQFd-BkL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "7",
    "ASIN": "B01EUK0EDS",
    "BRAND": "Ralph Lauren Black Label",
    "Title": "ralph lauren black label collection denim black shirt blouse 8 ",
    "Euclidean_similarity": "0.49825479399574546",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/413XLg2zN8L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "8",
    "ASIN": "B00E1LCYZI",
    "BRAND": "Allegra K",
    "Title": "allegra k women ruffled front long sleeves layered blouse black white xl ",
    "Euclidean_similarity": "0.49825479399574546",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41FcGdfT55L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "9",
    "ASIN": "B00O492QMI",
    "BRAND": "Gerry Webber",
    "Title": "gerry weber black black blouse 14 ",
    "Euclidean_similarity": "0.5097096621545399",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/5110bapaVBL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "10",
    "ASIN": "B01NBLNC7J",
    "BRAND": "Glo",
    "Title": "glo long sleeve black shirt sequins junior xlarge ",
    "Euclidean_similarity": "0.5097096621545399",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/314MaZGEakL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "11",
    "ASIN": "B00N2FKJR4",
    "BRAND": "DIESEL",
    "Title": "diesel manga long sleeves shirt 00qxx xsmall black ",
    "Euclidean_similarity": "0.5097096621545399",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/412MQr3xm-L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "12",
    "ASIN": "B06Y6FH453",
    "BRAND": "Who What Wear",
    "Title": "wear womens vneck blouse black xxl ",
    "Euclidean_similarity": "0.5470891863421616",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31-E5DKrdPL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "13",
    "ASIN": "B06XH7HQ2T",
    "BRAND": "DKNY",
    "Title": "dkny ponte vneck ruffled top black ",
    "Euclidean_similarity": "0.5470891863421616",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31Cv03VfQrL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "14",
    "ASIN": "B00XIM5SCC",
    "BRAND": "Active USA",
    "Title": "4 pack active basic womens cami tank top med black black black black ",
    "Euclidean_similarity": "0.5470891863421616",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31aFFNwNp6L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "15",
    "ASIN": "B01MZFZOFD",
    "BRAND": "Unomatch",
    "Title": "unomatch women loose plus size lace decorated sleeves blouse black 18 black ",
    "Euclidean_similarity": "0.5552504100033393",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41iPZYU9eDL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "16",
    "ASIN": "B01LXPGQAU",
    "BRAND": "Byoung",
    "Title": "byoung womens frisca womens black long shirt size 40 black ",
    "Euclidean_similarity": "0.5552504100033393",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/51wSPSfm7RL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "17",
    "ASIN": "B00XQBTD4Y",
    "BRAND": "Active USA",
    "Title": "4 pack active basic womens plus size tank top 2x black black black black ",
    "Euclidean_similarity": "0.5562398430198167",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31hV60pzQaL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "18",
    "ASIN": "B00WV4FI32",
    "BRAND": "Active Products",
    "Title": "4 pack active basic womens plus size tank tops 3x black black black black ",
    "Euclidean_similarity": "0.5562398430198167",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31aFFNwNp6L._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "19",
    "ASIN": "B00XQBT51A",
    "BRAND": "Active USA",
    "Title": "4 pack active basic womens plus size tank top 1x black black black black ",
    "Euclidean_similarity": "0.5562398430198167",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/31hV60pzQaL._SL160_.jpg",
    "Model": "bag_of_words",
  },
  {
    "id": "20",
    "ASIN": "B01JS2A3BG",
    "BRAND": "Dresswell",
    "Title": "dresswell black long sleeve chiffon blouse shirt loose casual women ",
    "Euclidean_similarity": "0.5614709903464854",
    "Image_URL": "https://images-na.ssl-images-amazon.com/images/I/41zvSaxMZuL._SL160_.jpg",
    "Model": "bag_of_words",
  },
];

export default recom;